#!/bin/sh

dir=${2-/tmp}

case $1 in
  *.tar)
    tar -xvf "$1" -C "$dir"
    ;;
  *.tar.gz|*.tar.Z)
    tar zxvf "$1" -C "$dir"
    ;;
  *.tar.bz2)
    tar jxvf "$1" -C "$dir"
    ;;
  *.tar.xz)
    xz -dc "$1" | tar xfv - -C "$dir"
    ;;
  *)
    echo "$1"'Unknown Compressed file' 1>&2
    exit 1
    ;;
esac